services:
  db:
    image: postgres:16
    env_file:
      - .env
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - "datos_postgres:/var/lib/postgresql/data"
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
     DB_HOST: db
    env_file:
      - .env
    depends_on:
      - db
volumes:
  datos_postgres:

