services:
  db:
    image: postgres:16
    env_file:
      - .env
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 2s
      retries: 5
      start_period: 5s
      timeout: 5s
    ports:
      - "5432:5432"
    volumes:
      - "datos_postgres:/var/lib/postgresql/data"
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
     DB_HOST: db
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
        restart: true 
    volumes:
      - .:/app
      - /app/venv
volumes:
  datos_postgres:

